---
modules-search: [ local, /usr/lib/calamares/modules ]

instantiate:
    - partitioning
    - users
    - network
    - packages
    - bootloader

sequence:
    - show:
        - welcome
        - locale
        - keyboard
        - partition
        - users
        - network
        - summary
    - exec:
        - partition
        - mount
        - unpackfs
        - network
        - users
        - bootloader
        - grubcfg
        - packages
        - fstab
        - locale
        - keyboard
        - localecfg
        - users
        - displaymanager
        - initcpio
        - unmount
    - show:
        - finished
